# Ports are defined here because we only want to open them
# for the development build.

services:
  frontend:
    ports:
      - '3000:3000'
  sql:
    ports:
      - '54321:5432'
  backend:
    ports:
      - '8080:4200'